/**
 * CHARACTERS — the human cast, Pip the cat, and Mote the Echo companion.
 *
 * Humans are entirely generated by `lib/humanoid.ts`: this file only decides
 * *who* each person is (build, garment, hair, colours, posture) and which poses
 * they need. That split is deliberate — an NPC's identity should be a dozen
 * lines of casting, never a dozen lines of pixel pushing.
 *
 * Casting rules used here:
 *   - Silhouette before colour. Cover the palette and Sera (long coat), Mira
 *     (apron + bun), Oren (slim + cap), Tavi (tall + wide stance), Nia (long
 *     hair, arms in), Elia (stout + wide hat) must still be distinguishable.
 *   - Every villager differs from every other villager in at least three of
 *     {build, height, hair style, outfit, palette}.
 *   - Hue is a character trait: Sera teal-grey, Mira warm red, Oren olive,
 *     Tavi orange, Nia blue, Elia plum, player green. Villagers take the six
 *     appended CLOTH_* ramps so they never poach a named character's colour.
 *
 * Pip and Mote are hand-drawn — a cat and a ball of light are not humanoids —
 * but they use the same mask/paint shading helpers, so they light identically.
 *
 * The runtime plays 'e' with flipX for west; no '_w' frames are generated.
 */
import { ArtBuild } from '../lib/registry.js';
import {
  charStrip, POSE_FPS, POSE_ONCE, mask, paint, limb, shift,
  type CharSpec, type Dir, type Pose,
} from '../lib/humanoid.js';
import { Surface } from '../lib/pixel.js';
import * as P from '../lib/palette.js';

const DIRS: Dir[] = ['s', 'n', 'e'];

function registerHuman(b: ArtBuild, who: string, spec: CharSpec, poses: Pose[]): void {
  for (const pose of poses) {
    for (const dir of DIRS) {
      b.addStrip(`char/${who}/${pose}_${dir}`, charStrip(spec, dir, pose), {
        key: `${who}_${pose}_${dir}`,
        frameRate: POSE_FPS[pose],
        repeat: POSE_ONCE[pose] ? 0 : -1,
      });
    }
  }
}

/** The pose set every speaking character needs (plan.md §55). */
const SPEAKING: Pose[] = ['idle', 'walk', 'talk', 'surprised', 'happy'];
/** Background townsfolk: enough to keep a street alive. */
const EXTRA: Pose[] = ['idle', 'walk', 'talk'];

// ── The cast ───────────────────────────────────────────────────────────────

const CAST: Array<{ who: string; spec: CharSpec; poses: Pose[] }> = [
  {
    // The player: green traveller, deliberately the plainest silhouette in the
    // game so the customisation sliders have somewhere to go.
    who: 'player',
    spec: {
      skin: 'fair', hair: 'brown', hairStyle: 'short',
      cloth: 'player', cloth2: 'neutral', outfit: 'tunic',
      build: 'normal', weapon: true,
    },
    poses: ['idle', 'walk', 'talk', 'surprised', 'happy', 'attack', 'dash'],
  },
  {
    // Sera: swallowed by an oversized coat, notebook always in hand. The widest
    // silhouette of the cast, and the only one carrying two accessories.
    who: 'sera',
    spec: {
      skin: 'warm', hair: 'auburn', hairStyle: 'messy',
      cloth: 'sera', cloth2: 'cream', outfit: 'coat',
      accessory: ['satchel', 'notebook', 'goggles'],
      build: 'normal', heightAdj: 1, armGap: 1,
    },
    poses: SPEAKING,
  },
  {
    // Mira: innkeeper. Red dress under a big working apron, hair up and out of
    // the way, stout and planted. Carries a basket on delivery runs.
    who: 'mira',
    spec: {
      skin: 'warm', hair: 'auburn', hairStyle: 'bun',
      cloth: 'mira', cloth2: 'apron', outfit: 'apron',
      accessory: 'basket', build: 'stout',
    },
    poses: [...SPEAKING, 'carry', 'sit'],
  },
  {
    // Oren: courier. Everything about him is narrow and quick — slim build,
    // tall, cropped hair under a cap, bag riding on one hip.
    who: 'oren',
    spec: {
      skin: 'olive', hair: 'black', hairStyle: 'cropped',
      cloth: 'oren', cloth2: P.CLOTH_SLATE, outfit: 'jacket',
      accessory: ['cap', 'bag'], build: 'slim', heightAdj: 1, armGap: -1,
    },
    poses: SPEAKING,
  },
  {
    // Tavi: the loudest person in the valley. Tallest, widest stance, a sash he
    // certainly chose himself.
    who: 'tavi',
    spec: {
      skin: 'warm', hair: 'rust', hairStyle: 'wild',
      cloth: 'tavi', cloth2: 'cream', outfit: 'tunic',
      accessory: 'sash', build: 'normal', heightAdj: 2, stance: 2, armGap: 1,
    },
    poses: SPEAKING,
  },
  {
    // Nia: smallest, quietest. Long hair reads as a single soft mass and her
    // arms stay pinned to her sides until the conformity scene.
    who: 'nia',
    spec: {
      skin: 'fair', hair: 'black', hairStyle: 'long',
      cloth: 'nia', cloth2: 'neutral', outfit: 'dress',
      accessory: 'none', build: 'slim', heightAdj: -1, stance: -1, armGap: -1,
    },
    poses: SPEAKING,
  },
  {
    // Mayor Elia: plum robe, enormous hat, clipboard she keeps losing.
    who: 'elia',
    spec: {
      skin: 'brown', hair: 'ash', hairStyle: 'bun',
      cloth: 'elia', cloth2: 'cream', outfit: 'robe',
      accessory: ['wide_hat', 'notebook'], build: 'stout', stance: 1,
    },
    poses: SPEAKING,
  },

  // ── Background townsfolk ────────────────────────────────────────────────
  {
    // a — the smallholder. Bald, stout, overalls: the widest low silhouette.
    who: 'villager_a',
    spec: {
      skin: 'warm', hair: 'brown', hairStyle: 'bald',
      cloth: P.CLOTH_MOSS, cloth2: P.CLOTH_WHEAT, outfit: 'overalls',
      build: 'stout', heightAdj: -1, stance: 1,
    },
    poses: EXTRA,
  },
  {
    // b — braid, berry dress, slim and tall. Reads as a vertical line.
    who: 'villager_b',
    spec: {
      skin: 'deep', hair: 'black', hairStyle: 'braid',
      cloth: P.CLOTH_BERRY, cloth2: 'cream', outfit: 'dress',
      accessory: 'flower', build: 'slim', heightAdj: 1,
    },
    poses: EXTRA,
  },
  {
    // c — the bookish one. Curly mass up top, waistcoat, glasses.
    who: 'villager_c',
    spec: {
      skin: 'brown', hair: 'ash', hairStyle: 'curly',
      cloth: P.CLOTH_SLATE, cloth2: P.CLOTH_WHEAT, outfit: 'vest',
      accessory: 'glasses', build: 'normal',
    },
    poses: EXTRA,
  },
  {
    // d — the traveller-in-town. Long coat and a scarf; only villager whose
    // hem moves as much as Sera's.
    who: 'villager_d',
    spec: {
      skin: 'olive', hair: 'teal', hairStyle: 'ponytail',
      cloth: P.CLOTH_SAGE, cloth2: P.CLOTH_CLAY, outfit: 'coat',
      accessory: 'scarf', build: 'slim', heightAdj: 1, armGap: -1,
    },
    poses: EXTRA,
  },
  {
    // e — the market seller. Stout with long hair over a plain clay tunic; the
    // apron silhouette is reserved for Mira so the innkeeper stays unique.
    who: 'villager_e',
    spec: {
      skin: 'fair', hair: 'blonde', hairStyle: 'long',
      cloth: P.CLOTH_CLAY, cloth2: P.CLOTH_WHEAT, outfit: 'tunic',
      accessory: 'basket', build: 'stout', stance: 1,
    },
    poses: [...EXTRA, 'carry'],
  },
  {
    // f — the labourer. Wide hat, wheat jacket, heavy stance, short.
    who: 'villager_f',
    spec: {
      skin: 'warm', hair: 'rust', hairStyle: 'short',
      cloth: P.CLOTH_WHEAT, cloth2: P.CLOTH_SLATE, outfit: 'jacket',
      accessory: 'wide_hat', build: 'normal', heightAdj: -1, stance: 1, armGap: 1,
    },
    poses: EXTRA,
  },
];

// ── PIP ────────────────────────────────────────────────────────────────────
//
// 16 x 14. Mascot rules: the head is nearly half the sprite, the eyes are huge,
// and the tail is never still. Everything expressive lives in the ears, the
// eyes and the tail — the body is just a warm shape to hang them off.

const PW = 16;
const PH = 14;
const PIP_DARK = shift(P.PIP_FUR, -3);

interface PipPose {
  headDX?: number; headDY?: number;
  bodyDY?: number;
  /** Tail tip, in sprite coordinates. */
  tail: [number, number];
  tailMid?: [number, number];
  ears?: 'up' | 'flat' | 'perk';
  eyes?: 'open' | 'blink' | 'wide' | 'happy';
  legPhase?: number;
  sit?: boolean;
  shadow?: boolean;
}

function pipCat(dir: Dir, o: PipPose): Surface {
  const s = new Surface(PW, PH);
  const M = '#ffffff';
  const east = dir === 'e';
  const sit = o.sit ?? false;
  const hdx = o.headDX ?? 0;
  const hdy = o.headDY ?? 0;
  const bdy = o.bodyDY ?? 0;
  if (o.shadow !== false) s.ellipse(3, PH - 2, 10, 2, P.SHADOW_CAST);

  // Geometry. The head is 8 of the 14 rows: Pip is mostly face, on purpose.
  const HY = 2 + hdy;
  const hw = east ? 8 : 10;
  const hx = (east ? 7 : 3) + hdx;
  const body = sit
    ? { x: 5, y: 6 + bdy, w: 6, h: 7 }
    : east
      ? { x: 1, y: 6 + bdy, w: 10, h: 6 }
      : { x: 4, y: 8 + bdy, w: 8, h: 5 };

  // Tail — the most expressive part of a cat, so it is drawn as a real curve
  // through a control point rather than a fixed hook.
  const root: [number, number] = east ? [2, body.y + 2] : [11, body.y + 1];
  const mid = o.tailMid ?? [(root[0] + o.tail[0]) / 2, (root[1] + o.tail[1]) / 2 - 2];
  const tail = mask((m) => {
    limb(m, root[0], root[1], Math.round(mid[0]), Math.round(mid[1]), 3, 2);
    limb(m, Math.round(mid[0]), Math.round(mid[1]), o.tail[0], o.tail[1], 2, 2);
  }, PW, PH);
  paint(s, tail, P.PIP_FUR, { kx: 0.5, ky: 0.4, bias: -0.1 });
  s.pxOver(Math.round(mid[0]), Math.round(mid[1]), PIP_DARK[1]);
  s.pxOver(Math.round((mid[0] + o.tail[0]) / 2), Math.round((mid[1] + o.tail[1]) / 2), PIP_DARK[1]);

  // Legs. Back legs one ramp step down so four legs read as four.
  const lp = o.legPhase ?? -1;
  const legs: Array<[number, number]> = sit
    ? [[5, 0], [9, 0]]
    : east
      ? [[2, 1], [4, 1], [8, 0], [10, 0]]
      : [[4, 1], [10, 1], [5, 0], [9, 0]];
  legs.forEach(([lx, front], i) => {
    const lift = lp >= 0 && i % 2 === lp % 2 ? (lp < 2 ? 1 : 0) : 0;
    const top = body.y + body.h - 3;
    const leg = mask((m) => { m.rect(lx, top, 2, PH - top - lift, M); }, PW, PH);
    paint(s, leg, front ? P.PIP_FUR : shift(P.PIP_FUR, -2), { kx: 0.6, ky: 0.2 });
    s.pxOver(lx, PH - 1 - lift, P.PIP_CREAM[3]);
    s.pxOver(lx + 1, PH - 1 - lift, P.PIP_CREAM[2]);
  });

  // Body, one step darker than the head so the two masses never fuse.
  const bodyMask = mask((m) => { m.ellipse(body.x, body.y, body.w, body.h, M); }, PW, PH);
  paint(s, bodyMask, P.PIP_FUR, { kx: 0.5, ky: 0.45, bias: -0.14 });
  for (let i = 0; i < 2; i++) {                       // tabby bars
    const bx = east ? body.x + 3 + i * 3 : body.x + 2 + i * 4;
    s.pxOver(bx, body.y + 1, PIP_DARK[1]);
    s.pxOver(bx, body.y + 2, PIP_DARK[0]);
  }
  if (!east && !sit) {
    const chest = mask((m) => { m.ellipse(6, body.y + 1, 4, 4, M); }, PW, PH);
    paint(s, chest, P.PIP_CREAM, { kx: 0.5, ky: 0.4 });
  }

  // Ears go under the head so their bases disappear into the skull.
  const ears = o.ears ?? 'up';
  const earMask = mask((m) => {
    if (ears === 'flat') {
      // pinned back and sideways — pure fear silhouette
      m.poly([[hx - 2, HY + 3], [hx + 2, HY], [hx + 2, HY + 4]], M);
      m.poly([[hx + hw + 1, HY + 3], [hx + hw - 3, HY], [hx + hw - 3, HY + 4]], M);
    } else {
      const tip = Math.max(0, HY - (ears === 'perk' ? 4 : 3));
      m.poly([[hx + 1, tip], [hx - 1, HY + 3], [hx + 4, HY + 3]], M);
      m.poly([[hx + hw - 2, tip], [hx + hw - 5, HY + 3], [hx + hw, HY + 3]], M);
    }
  }, PW, PH);
  paint(s, earMask, P.PIP_FUR, { kx: 0.5, ky: 0.6 });
  if (ears !== 'flat' && dir !== 'n') {
    const inner = mask((m) => {
      m.poly([[hx + 1, HY - 2], [hx + 0, HY + 2], [hx + 3, HY + 2]], M);
      m.poly([[hx + hw - 2, HY - 2], [hx + hw - 4, HY + 2], [hx + hw - 1, HY + 2]], M);
    }, PW, PH);
    for (let y = 0; y < PH; y++) for (let x = 0; x < PW; x++) {
      if (inner.alphaAt(x, y)) s.pxOver(x, y, P.PIP_PINK, 0.9);
    }
  }

  // Head.
  const head = mask((m) => { m.ellipse(hx, HY, hw, 8, M); }, PW, PH);
  paint(s, head, P.PIP_FUR, { kx: 0.45, ky: 0.4, bias: 0.06 });
  // Jaw line: 1px darker along the head's lower edge wherever the body is
  // behind it. Without this the cat is one continuous lump of fur.
  for (let x = 0; x < PW; x++) {
    for (let y = PH - 1; y >= 0; y--) {
      if (head.alphaAt(x, y) === 0) continue;
      if (bodyMask.alphaAt(x, y + 1) || bodyMask.alphaAt(x, y)) s.pxOver(x, y, PIP_DARK[0], 0.55);
      break;
    }
  }
  for (let i = 0; i < 3; i++) {                       // forehead stripes
    const sx = hx + 2 + i * 2 + (east ? 1 : 0);
    s.pxOver(sx, HY + 1, PIP_DARK[1]);
    if (i !== 1) s.pxOver(sx, HY + 2, PIP_DARK[0]);
  }

  // Face.
  const eyes = o.eyes ?? 'open';
  const eye = (ex: number, ey: number) => {
    switch (eyes) {
      case 'blink':
        s.pxOver(ex, ey + 1, P.OUTLINE);
        s.pxOver(ex + 1, ey + 1, P.OUTLINE);
        break;
      case 'happy':
        s.pxOver(ex - 1, ey + 1, P.OUTLINE);
        s.pxOver(ex, ey, P.OUTLINE);
        s.pxOver(ex + 1, ey + 1, P.OUTLINE);
        break;
      case 'wide':
        s.rect(ex - 1, ey - 1, 3, 4, P.OUTLINE);
        s.rect(ex, ey, 1, 2, P.LANTERN[2]);
        s.px(ex, ey, P.LANTERN[4]);
        break;
      default:
        s.rect(ex, ey, 2, 2, P.OUTLINE);
        s.px(ex, ey, P.LANTERN[3]);
        s.px(ex + 1, ey + 1, P.LANTERN[1]);
        break;
    }
  };
  if (dir === 'n') {
    s.pxOver(hx + 4, HY + 4, PIP_DARK[1]);
    s.pxOver(hx + 5, HY + 5, PIP_DARK[1]);
  } else if (east) {
    const muz = mask((m) => { m.ellipse(hx + 3, HY + 4, 5, 4, M); }, PW, PH);
    paint(s, muz, P.PIP_CREAM, { kx: 0.5, ky: 0.4 });
    eye(hx + 3, HY + 3);
    s.pxOver(hx + 7, HY + 5, P.PIP_PINK);
    s.pxOver(hx + 6, HY + 6, PIP_DARK[0]);
    s.px(hx + 8, HY + 4, P.PIP_CREAM[0]);
    s.px(hx + 9, HY + 3, P.PIP_CREAM[1]);
  } else {
    const muz = mask((m) => { m.ellipse(hx + 3, HY + 4, 4, 4, M); }, PW, PH);
    paint(s, muz, P.PIP_CREAM, { kx: 0.5, ky: 0.4 });
    eye(hx + 1, HY + 3);
    eye(hx + hw - 3, HY + 3);
    s.pxOver(hx + 4, HY + 5, P.PIP_PINK);
    s.pxOver(hx + 5, HY + 5, P.PIP_PINK);
    s.pxOver(hx + 4, HY + 6, PIP_DARK[0]);
    s.pxOver(hx + 5, HY + 6, PIP_DARK[0]);
    s.px(hx - 1, HY + 5, P.PIP_CREAM[1]);
    s.px(hx + hw, HY + 5, P.PIP_CREAM[1]);
  }

  s.outline(P.OUTLINE);
  return s;
}

function registerPip(b: ArtBuild): void {
  // idle — tail flick and a slow blink. The tail never rests in the same place
  // twice, which is most of what sells a cat.
  const idle: Surface[] = [
    pipCat('s', { tail: [15, 6], tailMid: [13, 5] }),
    pipCat('s', { tail: [15, 4], tailMid: [14, 6], headDY: -1 }),
    pipCat('s', { tail: [14, 3], tailMid: [14, 6], headDY: -1, eyes: 'blink' }),
    pipCat('s', { tail: [15, 5], tailMid: [13, 4], ears: 'perk' }),
  ];
  b.addStrip('char/pip/idle', idle, { key: 'pip_idle', frameRate: 4, repeat: -1 });

  for (const dir of DIRS) {
    const frames: Surface[] = [];
    for (let f = 0; f < 4; f++) {
      const bob = f === 1 || f === 3 ? -1 : 0;
      const tailX = dir === 'e' ? 1 - (f % 2) : 15 - (f % 2);
      frames.push(pipCat(dir, {
        legPhase: f, bodyDY: bob, headDY: bob,
        tail: [tailX, 4 + (f % 2)],
        tailMid: [dir === 'e' ? 2 : 13, 4 + ((f + 1) % 2)],
      }));
    }
    b.addStrip(`char/pip/walk_${dir}`, frames, { key: `pip_walk_${dir}`, frameRate: 8, repeat: -1 });
  }

  // scared — the Quest One pose. Ears pinned, body dropped, eyes blown wide,
  // tail tucked low, and a 1px tremble between the two frames.
  const scared = [0, 1].map((f) => {
    const s = pipCat('s', {
      ears: 'flat', eyes: 'wide', bodyDY: 2, headDY: 2 + (f ? 0 : 1),
      headDX: f ? -1 : 0, tail: [14, 12], tailMid: [13, 11],
    });
    return f ? s.offset(1, 0) : s;
  });
  b.addStrip('char/pip/scared', scared, { key: 'pip_scared', frameRate: 9, repeat: -1 });

  // hide — peering out from under furniture. The dark band is the underside of
  // whatever he has wedged himself beneath.
  const hide = [0, 1].map((f) => {
    const s = pipCat('s', {
      ears: 'flat', eyes: f ? 'blink' : 'wide', headDY: 4, bodyDY: 6,
      tail: [14, 13], tailMid: [13, 13], shadow: false,
    });
    const out = new Surface(PW, PH);
    out.blit(s);
    for (let y = 0; y < 5; y++) {
      for (let x = 0; x < PW; x++) out.px(x, y, P.OUTLINE, y === 4 ? 0.85 : 1);
    }
    // everything still under the ledge gets a violet shade, not a black one
    for (let y = 5; y < 8; y++) for (let x = 0; x < PW; x++) out.pxOver(x, y, P.OUTLINE, 0.34 - (y - 5) * 0.1);
    return out;
  });
  b.addStrip('char/pip/hide', hide, { key: 'pip_hide', frameRate: 2, repeat: -1 });

  const happy = [0, 1].map((f) => pipCat('s', {
    eyes: 'happy', ears: 'perk', headDY: -f, bodyDY: -f,
    tail: [13, 1 - f], tailMid: [13, 5],
  }));
  b.addStrip('char/pip/happy', happy, { key: 'pip_happy', frameRate: 5, repeat: -1 });

  const sit = [0, 1].map((f) => pipCat('s', {
    sit: true, headDY: f ? -1 : 0, eyes: f ? 'blink' : 'open',
    tail: [14, 12], tailMid: [13, 10],
  }));
  b.addStrip('char/pip/sit', sit, { key: 'pip_sit', frameRate: 2, repeat: -1 });
}

// ── MOTE ───────────────────────────────────────────────────────────────────
//
// 12 x 12, no outline and no face: a light source, not a creature. It emotes
// with shape, brightness and motion only. Layer order is always the same —
// violet haze, cyan body, white-hot core — so every emotion is the same lamp.

const MW = 12;
const MH = 12;

interface MoteOpts {
  cx?: number; cy?: number;
  r?: number;
  /** >1 stretches along x, <1 along y. */
  sx?: number; sy?: number;
  /** Shear per row — the whole body leans, which is Mote's head-tilt. */
  lean?: number;
  bright?: number;      // 0..1 multiplier on the core
  spikes?: number;      // flare count
  spikeLen?: number;
  /** Trailing wisps: [angle in radians, distance, size]. */
  wisps?: Array<[number, number, number]>;
  dim?: boolean;
}

function moteBall(o: MoteOpts = {}): Surface {
  const s = new Surface(MW, MH);
  const cx = o.cx ?? MW / 2;
  const cy = o.cy ?? MH / 2;
  const r = o.r ?? 3.6;
  const sx = o.sx ?? 1;
  const sy = o.sy ?? 1;
  const lean = o.lean ?? 0;
  const bright = o.bright ?? 1;
  const violet = o.dim ? shift(P.ECHO_VIOLET, -1) : P.ECHO_VIOLET;
  const cyan = o.dim ? shift(P.ECHO_CYAN, -1) : P.ECHO_CYAN;

  /** One elliptical shell, sheared by `lean`, composited with alpha. */
  const shell = (rad: number, color: string, alpha: number) => {
    for (let y = 0; y < MH; y++) {
      for (let x = 0; x < MW; x++) {
        const dy = y - cy;
        const dx = x - cx - lean * dy;
        const nx = dx / (rad * sx);
        const ny = dy / (rad * sy);
        if (nx * nx + ny * ny <= 1.05) s.px(x, y, color, alpha);
      }
    }
  };

  // Flare spikes go underneath so the body caps them cleanly.
  if (o.spikes) {
    for (let i = 0; i < o.spikes; i++) {
      const a = (i / o.spikes) * Math.PI * 2 + 0.3;
      const len = (o.spikeLen ?? 3);
      for (let t = 1; t <= len; t++) {
        const x = Math.round(cx + Math.cos(a) * (r + t - 0.5));
        const y = Math.round(cy + Math.sin(a) * (r + t - 0.5));
        s.px(x, y, t > len - 1 ? violet[3] : cyan[3], t > len - 1 ? 0.5 : 0.85);
      }
    }
  }

  shell(r + 2, violet[2], 0.3);
  shell(r + 1, violet[3], 0.55);
  shell(r, cyan[2], 0.9);
  shell(r - 1, cyan[3], 1);
  shell(r - 1.8, cyan[4], 1);
  // Core: the only near-white in town, and it is a light, so it is allowed.
  const core = Math.max(1, Math.round(r - 2.4));
  for (let j = 0; j < core; j++) {
    for (let i = 0; i < core; i++) {
      s.px(Math.round(cx - core / 2 + i), Math.round(cy - core / 2 + j - 0.3), P.MOTE_CORE, bright);
    }
  }

  // Wisps trail off the body rather than floating free: each is one step
  // smaller, dimmer and further out than the last.
  (o.wisps ?? []).forEach(([a, d, size], i) => {
    const wx = cx + Math.cos(a) * d;
    const wy = cy + Math.sin(a) * d;
    const col = i === 0 ? cyan[3] : violet[3];
    const al = i === 0 ? 0.8 : i === 1 ? 0.5 : 0.34;
    for (let j = 0; j < size; j++) {
      for (let k = 0; k < size; k++) {
        s.px(Math.round(wx + k - (size - 1) / 2), Math.round(wy + j - (size - 1) / 2), col, al);
      }
    }
  });
  return s;
}

function registerMote(b: ArtBuild): void {
  // idle — a bobbing pulse. Radius and core brightness breathe out of phase
  // with the vertical bob so it never looks like a blinking cursor.
  const idle: Surface[] = [];
  for (let f = 0; f < 6; f++) {
    const t = (f / 6) * Math.PI * 2;
    idle.push(moteBall({
      cy: 6 + Math.round(Math.sin(t) * 1.4),
      r: 3.5 + Math.sin(t + 1) * 0.5,
      bright: 0.8 + 0.2 * Math.cos(t),
      wisps: [
        [Math.PI / 2 + 0.35, 4.0 + Math.sin(t) * 0.5, 2],
        [Math.PI / 2 - 0.45, 5.0 - Math.sin(t) * 0.4, 1],
        [Math.PI / 2 + 1.0, 5.3, 1],
      ],
    }));
  }
  b.addStrip('char/mote/idle', idle, { key: 'mote_idle', frameRate: 8, repeat: -1 });

  // curious — the whole body leans over, wisps trailing behind the tilt. This
  // is Mote's head-tilt; it has no head to tilt.
  const curious: Surface[] = [0, 1, 2, 3].map((f) => {
    const lean = [0, -0.35, -0.5, -0.3][f];
    return moteBall({
      cy: 6, r: 3.6, sx: 1 + Math.abs(lean) * 0.25, sy: 1 - Math.abs(lean) * 0.1,
      lean, bright: 0.95,
      wisps: [
        [Math.PI / 2 - lean * 2, 4.2, 2],
        [Math.PI / 2 - lean * 3, 5.2, 1],
      ],
    });
  });
  b.addStrip('char/mote/curious', curious, { key: 'mote_curious', frameRate: 5, repeat: -1 });

  // alert — a hard spiky flare. Body shrinks, spikes shoot out, core whites.
  const alert: Surface[] = [0, 1, 2, 3].map((f) => moteBall({
    cy: 5, r: [3.2, 2.8, 3, 3.4][f],
    spikes: 8, spikeLen: [2, 4, 3, 2][f], bright: 1,
    wisps: [[Math.PI / 2, 5.4, 1]],
  }));
  b.addStrip('char/mote/alert', alert, { key: 'mote_alert', frameRate: 12, repeat: -1 });

  // point_<dir> — elongates toward the target, core riding the leading end.
  const pointDirs: Array<[Dir, number]> = [['s', Math.PI / 2], ['n', -Math.PI / 2], ['e', 0]];
  for (const [dir, a] of pointDirs) {
    const frames = [0, 1].map((f) => {
      const reach = 1.6 + f * 0.8;
      return moteBall({
        cx: 6 + Math.cos(a) * reach * 0.5,
        cy: 6 + Math.sin(a) * reach * 0.5,
        r: 3.3,
        sx: 1 + Math.abs(Math.cos(a)) * (0.35 + f * 0.2) - Math.abs(Math.sin(a)) * 0.15,
        sy: 1 + Math.abs(Math.sin(a)) * (0.35 + f * 0.2) - Math.abs(Math.cos(a)) * 0.15,
        bright: 1,
        wisps: [
          [a + Math.PI, 4.2 + f * 0.6, 2],
          [a + Math.PI + 0.55, 5.1 + f * 0.6, 1],
          [a + Math.PI - 0.55, 5.1 + f * 0.6, 1],
        ],
      });
    });
    b.addStrip(`char/mote/point_${dir}`, frames, { key: `mote_point_${dir}`, frameRate: 6, repeat: -1 });
  }

  // sad — dimmed, sunk low, wisps hanging straight down like a dripping tail.
  const sad = [0, 1].map((f) => moteBall({
    cy: 7 + f * 0.5, r: 3.2, sx: 1.1, sy: 0.85, dim: true, bright: 0.45,
    wisps: [[Math.PI / 2, 4.0 + f * 0.4, 2], [Math.PI / 2 + 0.3, 5.0, 1]],
  }));
  b.addStrip('char/mote/sad', sad, { key: 'mote_sad', frameRate: 2, repeat: -1 });
}

// ── Registration ───────────────────────────────────────────────────────────

export function registerCharacters(b: ArtBuild): void {
  for (const c of CAST) registerHuman(b, c.who, c.spec, c.poses);
  registerPip(b);
  registerMote(b);
}
