/**
 * Art-gap reporting.
 *
 * Placeholder frames are generated by the art build (tools/art/lib/guarantee.ts)
 * so the runtime never has to reason about missing textures. This module just
 * surfaces what got stubbed, for the QA harness and the workbench page.
 */
import Phaser from 'phaser';
import { art } from '@/world/art';

export function ensureFallbacks(_scene: Phaser.Scene): void {
  const stubbed = (art() as unknown as { stubbed?: string[] }).stubbed ?? [];
  (window as unknown as { __missingArt: string[] }).__missingArt = stubbed;
  if (stubbed.length) {
    console.warn(`[psyche] ${stubbed.length} art frame(s) are placeholders:`, stubbed);
  }
}
